import './components/header/input-hover';
import './components/header/open-menu';
import './components/header/close-menu';
import './components/header/current-page';
import './components/header/menu-current-page';
import './components/ArticlesSearchAPI/ArticlesSearchAPI.js';
import './components/TimesNewswireAPI/TimesNewswireAPI';
// import './components/MostPopularAPI/MostPopularAPI';
import './components/render/render.js';
import './components/button/button.js';
import './components/favoriteNews/favoriteNews.js';
import './components/firebaseAPI/firebaseAPI.js';
import './components/footer/footer.js';
import './components/pre-loader/pre-loader.js';
import './components/main/main.js';
import './components/mode-switcher/mode-switcher.js';
// import './components/newsCard/newsCard.js';
import './components/pagination/pagination.js';
// import './components/readNews/readNews.js';
