import './components/header/input-hover';
import './components/header/open-menu';
import './components/header/close-menu';
import './components/header/current-page';
import './components/header/menu-current-page';
import './components/articlesSearch/articlesSearch.js';
import './components/timesNewswire/timesNewswire';
// import './components/mostPopular/mostPopular';
// import './components/render/render.js';
import './components/button/button.js';
import './components/favoriteNews/favoriteNews.js';
import './components/footer/footer.js';
import './components/preLoader/preLoader.js';
import './components/main/main.js';
// import './components/mode-switcher/mode-switcher.js';
// import './components/newsCard/newsCard.js';
import './components/pagination/pagination.js';
import './components/readNews/readNews.js';