import './components/localStorageService/localStorageService.js'
import './components/render/render.js';
import './components/modeSwitcher/modeSwitcher.js';
import './components/readNews/readNews.js';
import './components/header/input-hover';
import './components/header/open-menu';
import './components/header/close-menu';
import './components/header/current-page';
import './components/header/menu-current-page';
import './components/articlesSearch/articlesSearch.js';
import './components/newsCard/newsCard.js';
import './components/pagination/pagination.js';
import './components/footer/footer.js';
